[package]
name = "crystallib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]

[dev-dependencies]
serde_json = "1.0.132"
crystallib = { path = ".", features = ["serde"] }
